### ISSUE TITLE
export all enums

### ISSUE THREAD

**Issue by xiaoyu-tamu** [ScaleLeap/selling-partner-api-sdk#60]
![image](https://user-images.githubusercontent.com/33362998/114114010-85fe6680-98a5-11eb-90ac-f288a9e5299e.png)

I think it would be nice to import types/enums from root

```ts
import { OrderOrderStatusEnum,  or whatever enums/types/interfaces } from '@scaleleap/selling-partner-api-sdk';

```

or maybe use string/number literal types instead of enums

**Comment by moltar** [comment]
@xiaoyu-tamu There's a problem because this is generated from models, and models have duplicate names. That's why it's not possible to export from root.

But if you have any technical proposals, we can certainly look into it.

**Comment by xiaoyu-tamu** [comment]
You're right.

I never used OpenAPI generator before, i'm not sure if this is possible. 

map this

```
    /**
     * The current order status.
     * @type {string}
     * @memberof Order
     */
    OrderStatus: OrderOrderStatusEnum;
```

to 

```
    /**
     * The current order status.
     * @type {string}
     * @memberof Order
     */
    OrderStatus: 'Pending' | 'Unshipped' | 'PartiallyShipped' | 'Shipped' | 'Canceled' | 'Unfulfillable' | 'InvoiceUnconfirmed' | 'PendingAvailability';
```


So, we can get typesafe without export duplicated enums

**Comment by moltar** [comment]
@nguyentoanit please investigate if this is possible

**Comment by moltar** [comment]
@xiaoyu-tamu the problem is really not with OpenAPI, but with the way SP API models are designed. It should have been just one model, and no dups, or even if they for some reason wanted to split it up into multiple models, they should have ensured there were not any duplication of names and just namespace all of the entities, but they didn't do that :/

I am in favor of getting rid of enums, as I also think it is annoying to use them.

Hopefully @nguyentoanit can figure out a solution.
